cmake_minimum_required(VERSION 3.20.0 FATAL_ERROR)
#set(LLVM_PROJECT_HOME ${CMAKE_HOME_DIRECTORY}/llvm-project)
#set(LLVM_INSTALL ${LLVM_PROJECT_HOME}/build)
#set(LLVM_INCLUDE ${LLVM_INSTALL}/include)
#set(LLVM_LIBS ${LLVM_INSTALL}/lib)
set(LLVM_DIR "${CMAKE_HOME_DIRECTORY}/llvm-project/build/lib/cmake")
set(CMAKE_PREFIX_PATH ${CMAKE_HOME_DIRECTORY}/llvm-project/build/lib/cmake)
find_package(LLVM REQUIRED CONFIG)
message(STATUS "LLVM V ${LLVM_PACKAGE_VERSION}")
message(STATUS "Found LLVM ${LLVM_PACKAGE_VERSION}")
message(STATUS "Using LLVMConfig.cmake in: ${LLVM_DIR}")
include_directories(${LLVM_INCLUDE_DIRS})
separate_arguments(LLVM_DEFINITIONS_LIST NATIVE_COMMAND ${LLVM_DEFINITIONS})
add_definitions(${LLVM_DEFINITIONS_LIST})